version: "2.1"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "80:5000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: Passw0rd
      MYSQL_DATABASE: employee_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 5s
    restart: unless-stopped
